package gov.edu.ce.anm.promed.domain.enums;

public enum AppointmentType {


    FIRST_CONSULTATION,
    RETURN,
    EXAM_TOMOGRAPHY,
    EXAM_XRAY,
    EXAM_COMPLETE_BLOOD,
    EXAM_BETA_HCG,
    EXAM_ULTRASOUND,
    EXAM_ELECTROCARDIOGRAM,
    EXAM_URINE_ANALYSIS,
    EXAM_GLYCEMIA_TEST,
    EXAM_COLPOSCOPY,
    EXAM_MAGNETIC_RESONANCE,
    EXAM_ENDOSCOPY;
}
